### ISSUE TITLE
clarify need to create cards for the model

### ISSUE THREAD

**Issue by stevenqzhang** [sirupsen/anki-airtable#8]
can you clarify the readme section here

```
You will need to manually create the Produce model if it doesn't exist. You will ALSO need to create cards for the model because anki-airtable will NOT import records that don't generate any cards. So: (1) create the model, (2) create cards, (3) restart Anki with this plugin.

```

What does the model involve? Do the fields in the model need to be a subset of the view's columns? or do they merely need to intersect?

what does the cards involve? do i need to make one dummy card or cards for every record I want imported?

**Comment by sirupsen** [comment]
Did you figure this out? At this point, you're probably in a better position than I to update the README in a way others can understand.

**Comment by mkrcah** [comment]
The model is explained in the Anki manual, in the [Key Concepts](https://docs.ankiweb.net/#/getting-started?id=key-concepts) section. Look for  explanation of notes, fields, card types, and note types.
